services:
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    environment:
      # MONGO_URI:
      # SAS_TOKEN:
      # ACCOUNT_NAME:
      # CONTAINER_NAME:
      # TMDB_API_KEY:
      # TMDB_ACCESS_TOKEN:
      # ACCESS_TOKEN_KEY:
      # REFRESH_TOKEN_KEY:
      - NODE_ENV=production
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
